### ISSUE TITLE
Commit 6e0194bbb3241c5dbae57b91a68ba82b611d51b0 Broke Docker Image Build/Creation

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/Docker-CODE#103]
Commit 6e0194bbb3241c5dbae57b91a68ba82b611d51b0 broke the Docker container build, as the CollaboraOffice6.4 packages are not (yet) available in the apt repository configured by the script:

```
echo "deb https://collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu1804 /" > /etc/apt/sources.list.d/collabora.list
```

**Comment by timar** [comment]
Yes, it was a bit early to switch to 6.4 in this repo. But now CODE 6.4 is out.
