### ISSUE TITLE
Wrong author information in office documents

### ISSUE THREAD

**Issue by alexdetsch** [CollaboraOnline/Docker-CODE#14]
Hey,

I just noticed, that Andras Timar has perpetuated himself in all newly created OOXML-Office-documents.
<img width="224" alt="andras-timar" src="https://user-images.githubusercontent.com/2041432/27015337-f6f90404-4f0b-11e7-80bb-faf6d868f013.PNG">
Thats the situation in Word, but its nearly the same with Excel and PowerPoint-Documents.
Additionally the date for creation is set to when Andras created the template.

As you know, the OOXML-file-structure is based on a ZIP-archive of several files. So to solve this issue you "just" have to adjust the template.docx/docProps/core.xml and change the nodes "dc_creator" and "dcterms:created" to the names of all current editing users and ofcourse adapt the creation-timestamp:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <dcterms:created xsi:type="dcterms:W3CDTF">2016-10-13T07:11:00Z</dcterms:created>
   <dc:creator>Andras Timar</dc:creator>
   <dc:description />
   <dc:language>de-DE</dc:language>
   <cp:lastModifiedBy />
   <dcterms:modified xsi:type="dcterms:W3CDTF">2017-06-11T23:00:48Z</dcterms:modified>
   <cp:revision>3</cp:revision>
   <dc:subject />
   <dc:title />
</cp:coreProperties>
```

Not a very urgent issue, but it was quite confusing when we read, that the newly created document was from october last year and only written from Andras.
Thank you!

**Comment by timar** [comment]
@alexdetsch I don't think this report belongs to CollaboraOnline/Docker-CODE. Presumably you are ownCloud or Nextcloud user, and you got the docx templates from there. I removed the name 'Andras Timar' from the docx and xlsx templates of nexcloud/richdocuments and owncloud/richdocuments, and the next release will contain them. 

On the other hand, I see no API to change these templates upon new file creation, so you might want to submit a feature request to ownCloud/Nextcloud core, to support this.
