### ISSUE TITLE
connection error while connecting to collabora-service

### ISSUE THREAD

**Issue by smoebody** [CollaboraOnline/Docker-CODE#17]
i just set up a new collaboraOnline-server with docker and  when i try to open a document via nextcloud i get the following error on the collabora-server:
```
wsd-00025-00033 10:13:31.625209 [ websrv_poll ] ERR  Socket #20 SSL BIO error: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request (errno: Success)| ./net/SslSocket.hpp:273   
wsd-00025-00033 10:13:31.625410 [ websrv_poll ] ERR  Error while handling poll for socket #20 in websrv_poll: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request| ./net/Socket.hpp:474
```

NextCloud: 12.0.1
CollaboraOnline: 1.12.34

**Comment by cropse** [comment]
Hi, I assume you use the docker-compose from the nextcloud example.
after install the app, `Collabora Online server` would be as the same as your server domain, It is due to the nginx setting, if not, pls describe more detail about your docker file

**Comment by jlegido** [comment]
@smoebody assuming you have an infrastructure with a container running nextcloud and another running collabora please connect to each one of them and check connectivity and SSL certificate **in both directions**.

Example:

```
sudo  docker exec -ti nextcloud bash
curl https://collabora.kedu.cat
```
Expected output:

`
OK
`
Please try this and see what happens.

**Comment by smoebody** [comment]
This issue is long gone. i don't even remember, what it was. Closing
