### ISSUE TITLE
Question: How to Upgrade to Latest Version

### ISSUE THREAD

**Issue by stone212** [CollaboraOnline/Docker-CODE#30]
This is a question not an Issue but the Wiki is blank so I am here.

I run docker collabora/code successfully with NextCloud.  When it is time to upgrade to the latest version will the docker container upgrade itself or must I do something?

If there is a doc on this please link to it in the wiki?

**Comment by thebearon** [comment]
Pull a fresh image, ditch the old container, start a new one.
Normally you don't need to change anything in the config inside the container, but if you did, make the same changes in the new one, and you're good to go.
