### ISSUE TITLE
Is this Docker Image still has a user limit ?

### ISSUE THREAD

**Issue by judexzhu** [CollaboraOnline/Docker-CODE#31]
Is Docker-CODE still has a user limit?

from https://nextcloud.com/collaboraonline/
> Issue: Collabora Online doesn't handle my 100 users.
>This docker image is designed for home usage with a limited numbers of users and open documents. If you need a more scalable solution, consider a support subscription for a reliable, business-ready online office experience.

**Comment by timar** [comment]
Docker-CODE has a (soft) concurrent user limit of 10, and concurrent open document limit of 20. See also: https://www.collaboraoffice.com/code/#what_is_code
