### ISSUE TITLE
Czech spell-check

### ISSUE THREAD

**Issue by lachmanfrantisek** [CollaboraOnline/Docker-CODE#33]
Hi,
thanks for the code container-image. Would it be possible to add also Czech spell-check?

Would it be hard to set this by some environment variable to be able to add new languages easily, without code changes?

Thanks in advance!

**Comment by timar** [comment]
It is possible. Use the dictionaries environment variable. See also: https://www.collaboraoffice.com/code/

**Comment by lachmanfrantisek** [comment]
@timar  Thanks for the reply.

Good to know it is already implemented..;-) Just two notes:
- It would be nice to have some notes about env. vars in the README.
- There are some problems with the parsing of the environment variable:

set | loaded
--- | ---
`de_DE en_GB en_US fr_FR cs sk` | `cs_CZ en_US fr_FR en_GB`
`de_DE en_GB en_US fr_FR cs_CZ sk` | `cs_CZ en_US fr_FR en_GB`
`cs de_DE en_GB en_US fr_FR sk` | `de_DE en_US fr_FR en_GB`
`aa cs de_DE en_GB en_US fr_FR sk bb` | `cs_CZ de_DE en_US fr_FR sk_SK en_GB`
`de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru` | `en_US fr_FR it_IT nl_NL pt_BR en_GB nl_BE pt_PT es_ES`

--> It does not accept the first and the last one.

**Comment by lachmanfrantisek** [comment]
@timar weird. It can be a problem with docker-compose. If I found the problem, I will create a new issue.

Thanks.
