### ISSUE TITLE
Unable to open files in nextcloud

### ISSUE THREAD

**Issue by MisterT87** [CollaboraOnline/Docker-CODE#35]
Hi Guys :)

I have installed collabora images with docker-ce and using it with nextcloud / nginx-proxy and letsencrypt-companion.
I can access https://example.com:9980 (I am getting "OK" there)
I can access https://example.com:9980/loleaflet/dist/admin/admin.html without any problems...

In nextcloud (collabora) Settings - Collabora Online Server: https://example.com:9980

Now, when I click on (for example) .ods files -> I see the collabora Editor but It cant open any files (no connection to file).

Error Log:
[https://pastebin.com/16Ui7GGf](https://pastebin.com/16Ui7GGf)

I give up - I dont know howto fix (tried it for 7 hours now) :/
Hope anybody can help...

**Comment by MisterT87** [comment]
Nevermind, problem solved.
Was not a bug, was misconfiguration - sorry for it

**Comment by ben7244** [comment]
Please, Can explain your solution? because in your case

Thanks

**Comment by MisterT87** [comment]
First of all make an an own subdomain - this is really needed !
Make an docker volume and mount that dir where loolwsd.xml is (recommend - easier to make changes on it.
Also mount your ssl certs directory into collabora docker container.

Then make the following on loolwsd.xml:
server_name: <YOUR collabora SUBDOMAIN>:<LISTEN PORT>

Then search after `cert` in this Dokument and set the Path to your cert / key / ssl chain file ( /path/to/your/SSL/files.pem ).

Then you can start the container with:
`docker run -t -d -p 127.0.0.1:9980:9980 -e "domain=<your-dot-escaped-domain>" \
        -e "username=admin" -e "password=S3cRet" --restart always --cap-add MKNOD collabora/code`

HINT: Port option HAVE TO! stay on localhost (Remote access will be granted with right nginx proxy settings)
domain -> Is your collabora subdomain with slash escaped like this: `subdomain\\.example\\.com`
Thats it !

In my case: collabora could not find right ssl files.

**Comment by ben7244** [comment]
Thank you, I will try that.
