### ISSUE TITLE
Custom fonts does not rendered

### ISSUE THREAD

**Issue by eslym** [CollaboraOnline/Docker-CODE#41]
I tried to installed some custom ttf on /usr/local/share/fonts/truetype and then rebuild the docker image, the font get listed but doesnt rendered.

**Comment by eslym** [comment]
fixed after move the fonts to /usr/share/fonts instead of /usr/local/share/fonts

**Comment by zidekuls** [comment]
Hi, can you tell me that how did you edit the install-libreoffice.sh to build custom font?
