### ISSUE TITLE
BUG: DONT_GEN_SSL_CERT doesnt work

### ISSUE THREAD

**Issue by p53** [CollaboraOnline/Docker-CODE#46]
as i found ${DONT_GEN_SSL_CERT-set} probably should be ${DONT_GEN_SSL_CERT:-set} and even with that it won't work because start fails with message that it tries to open ca /etc/loolwsd/ca-chain.cert.pem which of course doesn't exist when this flag is set....

**Comment by farmio** [comment]
DONT_GEN_SSL_CERT is meant to be used if you want to use your own certificate. It could for example be bind-mounted into your docker container: `-v "/path/to/certificate.pem:/etc/loolwsd/ca-chain.cert.pem"`

If you want to disable ssl et all `-e "extra_params=--o:ssl.enable=false"` additionally should do the trick.

See https://www.collaboraoffice.com/code/docker/

**Comment by hnbakker** [comment]
Both if statements whitin the start-libreoffice.sh are invalid.
_**if test "${DONT_GEN_SSL_CERT-set}" == set; then
if test "${cert_domain-set}" == set; then**_

This script will generate ssl certificates when "DONT_GEN_SSL_CERT=set".
Which is completely the opposite  !!!
Suggest to change this line to:

if test -z ${DONT_GEN_SSL_CERT}; then

The other line:
if test ! -z ${cert_domain-set}; then

**Comment by timar** [comment]
From the documentation: 
> DONT_GEN_SSL_CERT	When this environment variable is set (is not ""), then startup script will not generate a new SSL certificate signed by a dummy CA. It is useful, if you want to use your own SSL certificate for some reason.

For me it works like this:
`docker run -t -i -p 9980:9980 -e "DONT_GEN_SSL_CERT=1" collabora/code`
