### ISSUE TITLE
text wrap for complete column formats and DISPLAYS all rows - 

### ISSUE THREAD

**Issue by ferdiga** [CollaboraOnline/Docker-CODE#47]
LOOLWSD
3.4.1 (git hash: 0ab49af)
LOKit
Collabora Office 5.3-60 (git hash: 25ec65b)
to reproduce:
selecting column, click "text wrap"
what happens:
collabora starts to scroll through all rows, to the end of the sheet , very very very slow-....
what should happen:
format the visible rows in the foreground (obviously) and format the invisible rows in the background (not displaying these)

**Comment by timar** [comment]
Thanks for reporting, this is a known bug. I hope we'll fix it soon.

**Comment by thebearon** [comment]
Fixed in CODE 4.0 RCs.
