### ISSUE TITLE
CSP error with Code 4.0.0.2 preveting it to open on all Chromium-based browsers

### ISSUE THREAD

**Issue by e-alfred** [CollaboraOnline/Docker-CODE#56]
Hello,

I tried to run the Docker container for CODE 4.0.0.2 (or latest), but no client could load the editor window. On most Chromium-based browsers (Vivaldi, Opera, Chrome) I got the following error in the browser console immediately after the `Waiting for page to render…` message:

`Refused to display in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors mydomain.com".`

I went back to CODE 3.4.2.1 and everything works perfectly using Nextcloud 15 and the Collabora 3.1.1 app. I am using an Apache reverse proxy with the default configuration from the documentation.

**Comment by e-alfred** [comment]
It seems like the bug is related to running the reverse proxy on a custom port which seems to cause problems. Older version before 4.0 didn't have this problem.

**Comment by thebearon** [comment]
This will be fixed in the next update, the respective bug report is [tdf#122451](https://bugs.documentfoundation.org/show_bug.cgi?id=122451).

**Comment by e-alfred** [comment]
@thebearon I hope you can soon push a new release candidate to the Docker Hub.
