### ISSUE TITLE
Cannot Find Default Username and Password

### ISSUE THREAD

**Issue by hifihedgehog** [CollaboraOnline/Docker-CODE#59]
My understanding was whenever left unspecified at install, admin was the default username and password but those don't seem to work for logging in at https://mydomainname.com:9980/loleaflet/dist/admin/admin.html. How and where do I get the username and password?

**Comment by aliceinwire** [comment]
From the little i investigated, 
you need to set up it by using -e option when you start the docker machine.
Explained here:
https://www.collaboraoffice.com/code/docker/
`$ docker run -t -d -p 127.0.0.1:9980:9980 -e "domain=<your-dot-escaped-domain>" \
        -e "username=admin" -e "password=S3cRet" --restart always collabora/code`

If you don't set username and password, you have no access to the administration panel in others way. AFAIK

Would be anyway nice to have some opinion of someone more involved with collabora online project.

**Comment by pptyasar** [comment]
how to load document in frontend @aliceinwire

**Comment by thebearon** [comment]
@pptyasar you need to set up a file sync&share solution like Nextcloud or ownCloud, for details see https://www.collaboraoffice.com/code/ .
Also, let's close this.
