### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by kevinfaguiar** [CollaboraOnline/Docker-CODE#69]
Is Libre Office Online project ready for production deployment? I mean, in the integration with Nextcloud does still exists the 20 concurrent connections notification as explained here: https://www.libreoffice.org/download/libreoffice-online/

Also, in the Libre Office Online it is not a limitation (the 20 user concurrent), however in Collabora it is?

**Comment by thebearon** [comment]
This is an issue tracker for the Collabora CODE Docker image/scripts. Questions related to LibreOffice Online can be asked at https://ask.libreoffice.org/
