### ISSUE TITLE
Redirect to home after document close.

### ISSUE THREAD

**Issue by burtininkai** [CollaboraOnline/Docker-CODE#73]
Howdy,

Using latest collabora docker image based, with latest stable 17th Nextcloud. Have such behaviour, after closing document in collabora, getting redirected to home on nextcloud, instead of location from where document is. Is it expected behavior or configuration issue on my side? 

Thank You in advance and thank You for amazing product.

**Comment by thebearon** [comment]
Thanks for the feedback! Please update your Collabora Online connector app in Nextcloud to the latest version, 3.4.6.
If the issue still persists, open a bug report in the app's repo: https://github.com/nextcloud/richdocuments/
