### ISSUE TITLE
Latest image container not starting with "Not found: storage.ssl.cert_file_path"

### ISSUE THREAD

**Issue by edergillian** [CollaboraOnline/Docker-CODE#74]
When trying to deploy collabora/code:latest ("Id": "sha256:0de59a806d10e3215de161f8160f8924a67d3240275d8c2ae703607d2a6bed22"), using the same working docker-compose file for the image I had before ( "Id": "sha256:801fe8cc151303a44e426676e9056b733556f9b65165246ab2634c207f42cee5"; this image is no longer available to download), the container fails to start with the message:

"Not found: storage.ssl.cert_file_path"

Here's my docker-compose file:
 `version: "3.2"

services:
  collabora:
    image: collabora/code
    env_file: ./app/collabora.env
    volumes:
      - ./app/config/loolwsd.xml:/etc/loolwsd/loolwsd.xml
      - ./certs/cert.key:/etc/loolwsd/cert.key
      - ./certs/cert.ca-bundle:/etc/loolwsd/cert.ca-bundle
      - ./certs/cert.crt:/etc/loolwsd/cert.crt
    cap_add:
      - MKNOD
    ports:
      - 9980
  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/cert.crt:/etc/nginx/cert.crt
      - ./certs/cert.ca-bundle:/etc/nginx/cert.ca-bundle
      - ./certs/cert.key:/etc/nginx/cert.key
    ports:
      - 8443:443`

And here's the relevant part of the loolwsd.xml:

`    <ssl desc="SSL settings">
        <enable>true</enable>
        <termination>false</termination>
        <cert_file_path>/etc/loolwsd/cert.crt</cert_file_path>
        <key_file_path>/etc/loolwsd/cert.key</key_file_path>
        <ca_file_path>/etc/loolwsd/cert.ca-bundle</ca_file_path>
    .
    .
    .
    </ssl>`

I can say for sure that the file is in the container (copied it from the container and compared with the one outside). Both of the services use the same file and the nginx container works just fine.

Were there any changes to the loolwsd.xml file syntax?

Thanks in advance!

EDIT: Passing all file paths through "extra_params" environment variable solves the problem.

**Comment by blubbsy** [comment]
I'm having the same issue and would like to know what is supposed to be the correct proceeding in fixing this. Is passing the parameters through nginx the recommended way?

I also have this problem with the collabora version from the repository.

**Comment by timar** [comment]
There are two ssl configuration groups in loolwsd.xml now. 
1. SSL encryption between browser and loolwsd
2. SSL encryption between storage and loolwsd (this is new)

**Comment by itto-ogami** [comment]
<ssl desc="SSL settings">
            <enable type="bool" desc="Controls whether SSL encryption between storage and loolwsd is enabled. Defaults when empty to following the ssl.enable setting"></enable>
            <cert_file_path desc="Path to the cert file" relative="false"></cert_file_path>
            <key_file_path desc="Path to the key file" relative="false"></key_file_path>
            <ca_file_path desc="Path to the ca file" relative="false"></ca_file_path>
            <cipher_list desc="List of OpenSSL ciphers to accept. If empty the defaults are used. These can be overriden only if absolutely needed."></cipher_list>
        </ssl>
    </storage>
