### ISSUE TITLE
how do I use this?

### ISSUE THREAD

**Issue by gforceg** [CollaboraOnline/Docker-CODE#81]
I'm confused. Is this a docker image that allows me to run a libre office suite in the browser? I have a working container running and I can view these URLs in the browser:

https://[HOST]/loleaflet/dist/admin/admin.html
https://[HOST]/hosting/capabilities
https://[HOST]/hosting/discovery

If I connect to the root URL: https://[HOST] I just get the HTTP 200 OK response.

How do I begin to create / edit documents in my browser? Is there a URL for that? Maybe this isn't the tool that I think it is.

**Comment by gforceg** [comment]
If I navigate to https://[HOST]/loleaflet/fafb01f/loleaflet.html then I get an error window with a toolbar. 

![image](https://user-images.githubusercontent.com/14267747/73875767-08f3df00-4813-11ea-9bb3-68eb3a1ae33f.png)

**Comment by thebearon** [comment]
CODE only handles file editing, you need a file sync&share solution as well, typically Nextcloud or ownCloud, there are steps for setting those up quickly using Docker here: https://www.collaboraoffice.com/code/

**Comment by gforceg** [comment]
thanks!
