### ISSUE TITLE
Question about collabora:latest

### ISSUE THREAD

**Issue by kevdogg** [CollaboraOnline/Docker-CODE#91]
I looked at your Dockerfile here on github and you are using 18.04 Ubuntu as the image base.

In my docker-compose.yml file I have the following:
    image: collabora/code:latest

When I pull this image and create a root shell into the container, it appears I'm using a xenial 16.04 release.  

```
#docker exec -it collabora /bin/bash
#apt install lsb-release
root@41772e036f4b:/# lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

Does the docker hub image: https://hub.docker.com/r/collabora/code/tags not use 18.04 as the base?

**Comment by thebearon** [comment]
It's 18.04 for me. Is that actually the latest CODE image with digest `fc4da63639f08d1166414ef6763bf521a1c927c18bd83a42aa588fc2b6615e35`?

**Comment by kevdogg** [comment]
I think I had a problem with the pull.  
I'm running
`fc4da63639f08d1166414ef6763bf521a1c927c18bd83a42aa588fc2b6615e35`

Its running bionic if I look at the /etc/apt/sources.list. 

Thanks for replying. I'll close the question.
