### ISSUE TITLE
impossible to install on synology

### ISSUE THREAD

**Issue by alexblav81** [CollaboraOnline/Docker-CODE#93]
Hello,

I want to install collabora on my Synology NAS outside the container relaunches itself and impossible to contact it through curl -v https: // ip: 9980

I used the following compose file
[log_collabora.txt](https://github.com/CollaboraOnline/Docker-CODE/files/4707083/log_collabora.txt)

:
   nextcloud_collabora:
     container_name: nextcloud_collabora
     image: collabora / code
     restart: always
     cap_add:
       - MKNOD
     environment:
       - domain = nextcloud.mondom.com
     ports:
       - 9980: 9980
     networks:
       nextcloud:

I did the same installation on an ubuntu without worry.
I have attached the log of the container after startup if it can help me out.

**Comment by thebearon** [comment]
` kit_spare_001 ] ERR  Failed to install seccomp syscall filter| common/Seccomp.cpp:233`

Based on the logs, it seems like the NAS doesn't have seccomp support.

**Comment by alexblav81** [comment]
Hello,

Thank you for your response and sorry for my late return. I have been doing seccomp research in the meantime. Having not found it, can you tell me what it is and how I can check it?

Is there any way to do without it?

Thank you
