### ISSUE TITLE
"color.startsWith is not a function" / bundle.js when adding borders

### ISSUE THREAD

**Issue by simmstein** [CollaboraOnline/Docker-CODE#95]
Hi, 

When I add borders to cells, nothing happens. An error is thrown if the console:

```
TypeError: color.startsWith is not a function19 bundle.js:44:26680
    setBorderStyle https://xxxxx/loleaflet/6144a6c/bundle.js:44
    onclick https:/xxxxx/loleaflet/6144a6c/loleaflet.html?WOPISrc=xxxxxxxx
```

Video: https://kim.deblan.fr/~simon/videos/bug_collabora.mp4

**Comment by timar** [comment]
Thanks for this bug report. It's been tracked already at https://bugs.documentfoundation.org/show_bug.cgi?id=133078
The fix is in CODE 4.2.4 that was released yesterday.
