### ISSUE TITLE
CJK characters are not supported while using online convert api

### ISSUE THREAD

**Issue by sidey** [CollaboraOnline/Docker-CODE#96]
### problem
Hi,I am trying to convert txt to pdf by collabora online api.but I found Chinese are not converted as expected.
I've tried to modify the profile in docker container and changed the Lang to c.UTF-8,but it still doesn't work.
except online convert api, online view and edit are doing well.
### collabora version.
the latest (June.12 2020) or 4.2.4

any suggestion or words might be helpful.

**Comment by timar** [comment]
Thanks for the bug report. Could you please give more details? What did you try exactly? We would like to reproduce the bug and fix it.

**Comment by sidey** [comment]
thanks for your replay:).
 my original text files as follows:
```
adfafdafd
asdfafdsa
qereqwer
测试
```
and I used curl or a simple html page to send ad request to my collabora online server to convert this txt file to pdf.
by curl 
```
curl -F "data=@test.txt" https://localhost:9980/lool/convert-to/pdf > out.pdf
```
by html page:
``` html
<html>
<form action="http://host:port/lool/convert-to/pdf" enctype="multipart/form-data" method="post">
    File: <input type="file" name="data"><br/>
    Format: <input type="text" name="format"><br/>
    <input type="submit" value="Convert">
</form>
</html>
```
and after convert was finished.the pdf I got
```
adfafdafd
asdfafdsa
qereqwer
���
```
I put my original txt file and converted pdf in the attatchments in case you need them.

thanks for your help :)

[test.pdf](https://github.com/CollaboraOnline/Docker-CODE/files/4785163/test.pdf)
[test.txt](https://github.com/CollaboraOnline/Docker-CODE/files/4785164/test.txt)

**Comment by sidey** [comment]
### Updates
I found a docx file with an English file name and Chinese contents are converted as expected,
but not with a Chinese filename.
cmd
``` bash
curl -F "data=@WeeklyBrief/南方.docx" http://10.71.20.70:9980/lool/convert-to/pdf > aaa.pdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14187    0     0  100 14187      0   5046  0:00:02  0:00:02 --:--:--  5050
```
and curl returned:
```
curl: (52) Empty reply from server
```

**Comment by timar** [comment]
> 
> [test.pdf](https://github.com/CollaboraOnline/Docker-CODE/files/4785163/test.pdf)
> [test.txt](https://github.com/CollaboraOnline/Docker-CODE/files/4785164/test.txt)

This is expected. Your text file is not encoded in UTF-8.

**Comment by timar** [comment]
> ```shell
> curl -F "data=@WeeklyBrief/南方.docx" http://10.71.20.70:9980/lool/convert-to/pdf > aaa.pdf
> curl: (52) Empty reply from server
> ```
This is a genuine bug, but not new. I see it in version 4.2.3 as well. I'll investigate.

**Comment by sidey** [comment]
> > 
> 
> > [test.pdf](https://github.com/CollaboraOnline/Docker-CODE/files/4785163/test.pdf)
> 
> > [test.txt](https://github.com/CollaboraOnline/Docker-CODE/files/4785164/test.txt)
> 
> 
> 
> This is expected. Your text file is not encoded in UTF-8. 

Thanks. I checked the txt file again ,and as you said,it’s not UTF-8 encoding.
And it works after I changed the encoding to UTF-8

**Comment by timar** [comment]
This is fixed in latest CODE release.
