### ISSUE TITLE
access_token is necessary while using online view

### ISSUE THREAD

**Issue by sidey** [CollaboraOnline/Docker-CODE#97]
### problem
I am using collabora office online to support online view of docx and xls in my app.
but I found access_token must be appended to the URL query or there will be an exception.
even a dummy access_token works.

### details
service url as follows
```
http://host:9980/loleaflet/a5d14f2/loleaflet.html
```
WOPISrc
```
http://wopihost:10080/wopi/files/1234
```
and this works
```
http://host:9980/loleaflet/a5d14f2/loleaflet.html?WOPISrc=http://wopihost:10080/wopi/files/1234&access_token=123
```
but this doesn't
```
http://host:9980/loleaflet/a5d14f2/loleaflet.html?WOPISrc=http://wopihost:10080/wopi/files/1234
```
a dialog with
```
Unauthorized WOPI host. Please try again later and report to your administrator if the issue persists.
```
was alerted

### reason
After I checked the logs and codes .I found the reason.
1. wsd/Storage.cpp getWOPIFileInfo()
``` cpp
 auth.authorizeRequest(request);
```
 this codes throwed a BadRequestException

2. common/Authorization.cpp authorizeRequest()
``` cpp
case Type::token:
   //balabla
case Type::Header:
  //balabla
default:
   throw BadRequestException("Invalid HTTP request type");
```

3. wsd/ClientSession  method getAuthorization()
``` cpp
if (param.first == "access_token")
     //balabla
    return Authorization(Authorization::Type::Token, decodedToken);
if (param.first == "access_header")
    return Authorization(Authorization::Type::Header, decodedHeader);

return Authorization(); // if access_token and access_header are not specified.

```

### at the last
I'm not sure this is a bug, or you want to make sure a token shoud be used. I'am using collabora online in personal use ,and token is optional.
BY THE WAY. an url without an access_token is working fine with office online service.

**Comment by thebearon** [comment]
The access_token is crucial so the WOPI host does not serve the file to any random incoming request. If you have an implementation for personal use, and for whatever reason don't care much about it, use a dummy access_token. It should never be omitted in a real world use-case.
