### ISSUE TITLE
Borders not working

### ISSUE THREAD

**Issue by DevDorrejo** [CollaboraOnline/Docker-CODE#98]
Hello, have CODE with NC 18.0.6 and the lasted rich document 3.7.2, on a document when i try to use the function borders the click wont work and neither can enter with the keyboard, pls look over this.

and the right panel, when click borders do nothing.

thank you.

**Comment by DevDorrejo** [comment]
hello?

**Comment by thebearon** [comment]
Click somewhere else on the sidebar, and then Borders.
